//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/InputActions/Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Controls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Controls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controls"",
    ""maps"": [
        {
            ""name"": ""Rumble"",
            ""id"": ""600fcf12-5520-4311-a8bf-9aa42f1b8134"",
            ""actions"": [
                {
                    ""name"": ""RumbleAction"",
                    ""type"": ""PassThrough"",
                    ""id"": ""af8e6ec5-7e60-4bc1-9d68-66aad9890bde"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""241a5f00-0b9a-4cb7-bb34-706ea4298797"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""RumbleAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4d3fad91-c429-499b-b1ef-1793755944fd"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""RumbleAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Buttons"",
            ""id"": ""3a18deff-cb2c-40dd-b347-935c37fa2975"",
            ""actions"": [
                {
                    ""name"": ""Accelerate"",
                    ""type"": ""Button"",
                    ""id"": ""1d1cb612-0a0b-4972-b9b1-80aa15d011c6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Brake"",
                    ""type"": ""Button"",
                    ""id"": ""f65f7f51-eff5-4922-80a1-7975f1547291"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LBumper"",
                    ""type"": ""Button"",
                    ""id"": ""d52c00ac-277b-48f0-9701-0de70e5f67e7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RBumper"",
                    ""type"": ""Button"",
                    ""id"": ""1e9d90c7-c70d-4737-baaf-8bca59bc8f23"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LDrift"",
                    ""type"": ""Value"",
                    ""id"": ""1ebcf712-0c12-4293-8574-4c594535c277"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RDrift"",
                    ""type"": ""Value"",
                    ""id"": ""4ed5484c-8afb-44c5-9cb6-075ae8f60f19"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Item"",
                    ""type"": ""Button"",
                    ""id"": ""1d3ca0ab-8ead-46d8-8ccc-70b4f75d8fc0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EditVehicle"",
                    ""type"": ""Button"",
                    ""id"": ""8e7af952-8d6f-4275-a5e9-7cac12d42c62"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Leaderboard"",
                    ""type"": ""Button"",
                    ""id"": ""b9daa74e-7e42-49f1-99ff-05b0c5cb7fd6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SetLang"",
                    ""type"": ""Button"",
                    ""id"": ""21a92ca7-5a42-4ef0-8aea-aed14e4cbcb4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Honk"",
                    ""type"": ""Button"",
                    ""id"": ""4db471f4-7446-43f4-b918-a1b0fd56e315"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""StartGame"",
                    ""type"": ""Button"",
                    ""id"": ""8641f6e1-61a2-47a1-9ae1-00fff5450d6e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c10ada85-73e3-4452-ad67-31649f7e2c5c"",
                    ""path"": ""<XInputController>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""LBumper"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""640cffcc-f7c7-4d24-bc6f-63a226235aee"",
                    ""path"": ""<DualShockGamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""LBumper"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b6d6cf74-36d4-4929-93a3-3e31cfa8c843"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""LBumper"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ad192a0c-1011-4590-9f3e-5b4ce9607cf4"",
                    ""path"": ""<XInputController>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""RBumper"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d181ee94-5faa-4188-841a-d1ae94b0b61a"",
                    ""path"": ""<DualShockGamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""RBumper"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f2a16e1b-35a2-4866-b3e9-3d1010474cf9"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""RBumper"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""26276292-8cc0-42dc-bc14-bc953648a73e"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Accelerate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""af50a657-bb1a-4ffa-b681-72918f7ea117"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Accelerate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a3d70354-f88d-4b0e-b8ba-dffde9b6ea48"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Brake"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""702395aa-5051-4241-b419-8dfe9dec4659"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Brake"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""14905671-6852-45c8-a894-a816d9ccf968"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""LDrift"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0386a532-bc47-4b0c-affb-8d3f2261cac7"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LDrift"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d82aa69b-642f-4d46-a8f7-13c2670d0b3f"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""RDrift"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""67753817-53a1-4bc1-81a3-94f4393fff5d"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RDrift"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c3ea56b6-fabc-46e0-b3bb-ff54ab515f23"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Item"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4d994b2e-d80e-461f-9f50-b3949a82fd67"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Item"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4f46e70d-3891-4edb-aa98-454fdab02dd9"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Item"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7fa987a5-be3b-404c-9830-d6546c896d3f"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""EditVehicle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""531b39c9-b0db-43dd-94a7-ef4c2791acff"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Leaderboard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e10674e7-d945-4392-addf-e9ad74e9d643"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SetLang"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f997ed12-2785-48dd-bb13-cd58152526ee"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Honk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""82b32589-0c44-4c23-9643-fd34fead3bf8"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""StartGame"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""General"",
            ""id"": ""82cb0f70-271d-446e-94ba-d26a4b5a7190"",
            ""actions"": [
                {
                    ""name"": ""Submit"",
                    ""type"": ""Button"",
                    ""id"": ""3e6ada78-2d84-4bf9-b4a9-077c37b7d9d8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Navigation"",
                    ""type"": ""Value"",
                    ""id"": ""bf0b07fb-3aa2-4f81-b939-4fb15eac8d43"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PageLeft"",
                    ""type"": ""Button"",
                    ""id"": ""bdb33773-d08c-4373-af56-c73a89d0a87b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PageRight"",
                    ""type"": ""Button"",
                    ""id"": ""c458f017-562c-4af9-a6dd-f6869e706f5b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Accept"",
                    ""type"": ""Button"",
                    ""id"": ""33a5b42f-ab4a-4e07-b510-a6d6625ff446"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cancel"",
                    ""type"": ""Button"",
                    ""id"": ""dd4128f5-c192-4638-9044-268dcf6ad702"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Level1"",
                    ""type"": ""Button"",
                    ""id"": ""f8dd8d80-18cf-4250-bd3e-2c82351670ce"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Level2"",
                    ""type"": ""Button"",
                    ""id"": ""ee3780ce-9d95-4333-93b7-70874685bd34"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Level3"",
                    ""type"": ""Button"",
                    ""id"": ""1939d0d4-cf9e-40dc-9617-3a4b16a88e66"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d1dda214-5eca-4139-b3c3-1e9a08373908"",
                    ""path"": ""<Keyboard>/anyKey"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3dc0547c-6064-4c1c-9b8a-783fe5ed3fa1"",
                    ""path"": ""*/{Submit}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Horizontal"",
                    ""id"": ""df72231c-cbc6-4c89-9b04-0b9a62e8f4f7"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigation"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""09f830b5-a19d-4a13-bab8-0c87b32c9478"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Navigation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""cd7a07b1-cd2c-41e0-80de-a38fd399c635"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""14199b85-0d39-499f-b9f8-86ba0baa3b0e"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""PageLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6975e2f0-2dd0-4f13-98a3-2977553c8db3"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""PageRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9bf12d0e-ab8f-4681-b047-a5d3010d5ea0"",
                    ""path"": ""<Keyboard>/numpadEnter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Accept"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b8af9291-75f6-4619-bff1-6d77a0da21cd"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Accept"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""17b86ded-fa4a-4833-9e99-c1be70d33f2c"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Accept"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9a3d1079-d60d-41ce-a77a-b244c28a2d16"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Accept"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5e5cfae4-3a67-4ae4-af77-bf23785713a5"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Accept"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ab5abf55-356a-4e3d-b1e0-02df70d68887"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cf0b7c7c-44f4-4c77-b608-31ec1670508d"",
                    ""path"": ""<Keyboard>/backspace"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b4e7c63a-51ec-421c-b1a2-c84a6d51e127"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""44f7510f-4bdc-4d8b-8b0a-297ba864a78d"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Level1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""db11c7d5-5c9c-4b36-89a2-f30ee89f8850"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Level2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4592ef1b-ed13-4141-a8b2-6469c373f336"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Level3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": []
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": []
        }
    ]
}");
        // Rumble
        m_Rumble = asset.FindActionMap("Rumble", throwIfNotFound: true);
        m_Rumble_RumbleAction = m_Rumble.FindAction("RumbleAction", throwIfNotFound: true);
        // Buttons
        m_Buttons = asset.FindActionMap("Buttons", throwIfNotFound: true);
        m_Buttons_Accelerate = m_Buttons.FindAction("Accelerate", throwIfNotFound: true);
        m_Buttons_Brake = m_Buttons.FindAction("Brake", throwIfNotFound: true);
        m_Buttons_LBumper = m_Buttons.FindAction("LBumper", throwIfNotFound: true);
        m_Buttons_RBumper = m_Buttons.FindAction("RBumper", throwIfNotFound: true);
        m_Buttons_LDrift = m_Buttons.FindAction("LDrift", throwIfNotFound: true);
        m_Buttons_RDrift = m_Buttons.FindAction("RDrift", throwIfNotFound: true);
        m_Buttons_Item = m_Buttons.FindAction("Item", throwIfNotFound: true);
        m_Buttons_EditVehicle = m_Buttons.FindAction("EditVehicle", throwIfNotFound: true);
        m_Buttons_Leaderboard = m_Buttons.FindAction("Leaderboard", throwIfNotFound: true);
        m_Buttons_SetLang = m_Buttons.FindAction("SetLang", throwIfNotFound: true);
        m_Buttons_Honk = m_Buttons.FindAction("Honk", throwIfNotFound: true);
        m_Buttons_StartGame = m_Buttons.FindAction("StartGame", throwIfNotFound: true);
        // General
        m_General = asset.FindActionMap("General", throwIfNotFound: true);
        m_General_Submit = m_General.FindAction("Submit", throwIfNotFound: true);
        m_General_Navigation = m_General.FindAction("Navigation", throwIfNotFound: true);
        m_General_PageLeft = m_General.FindAction("PageLeft", throwIfNotFound: true);
        m_General_PageRight = m_General.FindAction("PageRight", throwIfNotFound: true);
        m_General_Accept = m_General.FindAction("Accept", throwIfNotFound: true);
        m_General_Cancel = m_General.FindAction("Cancel", throwIfNotFound: true);
        m_General_Level1 = m_General.FindAction("Level1", throwIfNotFound: true);
        m_General_Level2 = m_General.FindAction("Level2", throwIfNotFound: true);
        m_General_Level3 = m_General.FindAction("Level3", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Rumble
    private readonly InputActionMap m_Rumble;
    private List<IRumbleActions> m_RumbleActionsCallbackInterfaces = new List<IRumbleActions>();
    private readonly InputAction m_Rumble_RumbleAction;
    public struct RumbleActions
    {
        private @Controls m_Wrapper;
        public RumbleActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @RumbleAction => m_Wrapper.m_Rumble_RumbleAction;
        public InputActionMap Get() { return m_Wrapper.m_Rumble; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(RumbleActions set) { return set.Get(); }
        public void AddCallbacks(IRumbleActions instance)
        {
            if (instance == null || m_Wrapper.m_RumbleActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_RumbleActionsCallbackInterfaces.Add(instance);
            @RumbleAction.started += instance.OnRumbleAction;
            @RumbleAction.performed += instance.OnRumbleAction;
            @RumbleAction.canceled += instance.OnRumbleAction;
        }

        private void UnregisterCallbacks(IRumbleActions instance)
        {
            @RumbleAction.started -= instance.OnRumbleAction;
            @RumbleAction.performed -= instance.OnRumbleAction;
            @RumbleAction.canceled -= instance.OnRumbleAction;
        }

        public void RemoveCallbacks(IRumbleActions instance)
        {
            if (m_Wrapper.m_RumbleActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IRumbleActions instance)
        {
            foreach (var item in m_Wrapper.m_RumbleActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_RumbleActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public RumbleActions @Rumble => new RumbleActions(this);

    // Buttons
    private readonly InputActionMap m_Buttons;
    private List<IButtonsActions> m_ButtonsActionsCallbackInterfaces = new List<IButtonsActions>();
    private readonly InputAction m_Buttons_Accelerate;
    private readonly InputAction m_Buttons_Brake;
    private readonly InputAction m_Buttons_LBumper;
    private readonly InputAction m_Buttons_RBumper;
    private readonly InputAction m_Buttons_LDrift;
    private readonly InputAction m_Buttons_RDrift;
    private readonly InputAction m_Buttons_Item;
    private readonly InputAction m_Buttons_EditVehicle;
    private readonly InputAction m_Buttons_Leaderboard;
    private readonly InputAction m_Buttons_SetLang;
    private readonly InputAction m_Buttons_Honk;
    private readonly InputAction m_Buttons_StartGame;
    public struct ButtonsActions
    {
        private @Controls m_Wrapper;
        public ButtonsActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Accelerate => m_Wrapper.m_Buttons_Accelerate;
        public InputAction @Brake => m_Wrapper.m_Buttons_Brake;
        public InputAction @LBumper => m_Wrapper.m_Buttons_LBumper;
        public InputAction @RBumper => m_Wrapper.m_Buttons_RBumper;
        public InputAction @LDrift => m_Wrapper.m_Buttons_LDrift;
        public InputAction @RDrift => m_Wrapper.m_Buttons_RDrift;
        public InputAction @Item => m_Wrapper.m_Buttons_Item;
        public InputAction @EditVehicle => m_Wrapper.m_Buttons_EditVehicle;
        public InputAction @Leaderboard => m_Wrapper.m_Buttons_Leaderboard;
        public InputAction @SetLang => m_Wrapper.m_Buttons_SetLang;
        public InputAction @Honk => m_Wrapper.m_Buttons_Honk;
        public InputAction @StartGame => m_Wrapper.m_Buttons_StartGame;
        public InputActionMap Get() { return m_Wrapper.m_Buttons; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ButtonsActions set) { return set.Get(); }
        public void AddCallbacks(IButtonsActions instance)
        {
            if (instance == null || m_Wrapper.m_ButtonsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ButtonsActionsCallbackInterfaces.Add(instance);
            @Accelerate.started += instance.OnAccelerate;
            @Accelerate.performed += instance.OnAccelerate;
            @Accelerate.canceled += instance.OnAccelerate;
            @Brake.started += instance.OnBrake;
            @Brake.performed += instance.OnBrake;
            @Brake.canceled += instance.OnBrake;
            @LBumper.started += instance.OnLBumper;
            @LBumper.performed += instance.OnLBumper;
            @LBumper.canceled += instance.OnLBumper;
            @RBumper.started += instance.OnRBumper;
            @RBumper.performed += instance.OnRBumper;
            @RBumper.canceled += instance.OnRBumper;
            @LDrift.started += instance.OnLDrift;
            @LDrift.performed += instance.OnLDrift;
            @LDrift.canceled += instance.OnLDrift;
            @RDrift.started += instance.OnRDrift;
            @RDrift.performed += instance.OnRDrift;
            @RDrift.canceled += instance.OnRDrift;
            @Item.started += instance.OnItem;
            @Item.performed += instance.OnItem;
            @Item.canceled += instance.OnItem;
            @EditVehicle.started += instance.OnEditVehicle;
            @EditVehicle.performed += instance.OnEditVehicle;
            @EditVehicle.canceled += instance.OnEditVehicle;
            @Leaderboard.started += instance.OnLeaderboard;
            @Leaderboard.performed += instance.OnLeaderboard;
            @Leaderboard.canceled += instance.OnLeaderboard;
            @SetLang.started += instance.OnSetLang;
            @SetLang.performed += instance.OnSetLang;
            @SetLang.canceled += instance.OnSetLang;
            @Honk.started += instance.OnHonk;
            @Honk.performed += instance.OnHonk;
            @Honk.canceled += instance.OnHonk;
            @StartGame.started += instance.OnStartGame;
            @StartGame.performed += instance.OnStartGame;
            @StartGame.canceled += instance.OnStartGame;
        }

        private void UnregisterCallbacks(IButtonsActions instance)
        {
            @Accelerate.started -= instance.OnAccelerate;
            @Accelerate.performed -= instance.OnAccelerate;
            @Accelerate.canceled -= instance.OnAccelerate;
            @Brake.started -= instance.OnBrake;
            @Brake.performed -= instance.OnBrake;
            @Brake.canceled -= instance.OnBrake;
            @LBumper.started -= instance.OnLBumper;
            @LBumper.performed -= instance.OnLBumper;
            @LBumper.canceled -= instance.OnLBumper;
            @RBumper.started -= instance.OnRBumper;
            @RBumper.performed -= instance.OnRBumper;
            @RBumper.canceled -= instance.OnRBumper;
            @LDrift.started -= instance.OnLDrift;
            @LDrift.performed -= instance.OnLDrift;
            @LDrift.canceled -= instance.OnLDrift;
            @RDrift.started -= instance.OnRDrift;
            @RDrift.performed -= instance.OnRDrift;
            @RDrift.canceled -= instance.OnRDrift;
            @Item.started -= instance.OnItem;
            @Item.performed -= instance.OnItem;
            @Item.canceled -= instance.OnItem;
            @EditVehicle.started -= instance.OnEditVehicle;
            @EditVehicle.performed -= instance.OnEditVehicle;
            @EditVehicle.canceled -= instance.OnEditVehicle;
            @Leaderboard.started -= instance.OnLeaderboard;
            @Leaderboard.performed -= instance.OnLeaderboard;
            @Leaderboard.canceled -= instance.OnLeaderboard;
            @SetLang.started -= instance.OnSetLang;
            @SetLang.performed -= instance.OnSetLang;
            @SetLang.canceled -= instance.OnSetLang;
            @Honk.started -= instance.OnHonk;
            @Honk.performed -= instance.OnHonk;
            @Honk.canceled -= instance.OnHonk;
            @StartGame.started -= instance.OnStartGame;
            @StartGame.performed -= instance.OnStartGame;
            @StartGame.canceled -= instance.OnStartGame;
        }

        public void RemoveCallbacks(IButtonsActions instance)
        {
            if (m_Wrapper.m_ButtonsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IButtonsActions instance)
        {
            foreach (var item in m_Wrapper.m_ButtonsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ButtonsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ButtonsActions @Buttons => new ButtonsActions(this);

    // General
    private readonly InputActionMap m_General;
    private List<IGeneralActions> m_GeneralActionsCallbackInterfaces = new List<IGeneralActions>();
    private readonly InputAction m_General_Submit;
    private readonly InputAction m_General_Navigation;
    private readonly InputAction m_General_PageLeft;
    private readonly InputAction m_General_PageRight;
    private readonly InputAction m_General_Accept;
    private readonly InputAction m_General_Cancel;
    private readonly InputAction m_General_Level1;
    private readonly InputAction m_General_Level2;
    private readonly InputAction m_General_Level3;
    public struct GeneralActions
    {
        private @Controls m_Wrapper;
        public GeneralActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Submit => m_Wrapper.m_General_Submit;
        public InputAction @Navigation => m_Wrapper.m_General_Navigation;
        public InputAction @PageLeft => m_Wrapper.m_General_PageLeft;
        public InputAction @PageRight => m_Wrapper.m_General_PageRight;
        public InputAction @Accept => m_Wrapper.m_General_Accept;
        public InputAction @Cancel => m_Wrapper.m_General_Cancel;
        public InputAction @Level1 => m_Wrapper.m_General_Level1;
        public InputAction @Level2 => m_Wrapper.m_General_Level2;
        public InputAction @Level3 => m_Wrapper.m_General_Level3;
        public InputActionMap Get() { return m_Wrapper.m_General; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GeneralActions set) { return set.Get(); }
        public void AddCallbacks(IGeneralActions instance)
        {
            if (instance == null || m_Wrapper.m_GeneralActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GeneralActionsCallbackInterfaces.Add(instance);
            @Submit.started += instance.OnSubmit;
            @Submit.performed += instance.OnSubmit;
            @Submit.canceled += instance.OnSubmit;
            @Navigation.started += instance.OnNavigation;
            @Navigation.performed += instance.OnNavigation;
            @Navigation.canceled += instance.OnNavigation;
            @PageLeft.started += instance.OnPageLeft;
            @PageLeft.performed += instance.OnPageLeft;
            @PageLeft.canceled += instance.OnPageLeft;
            @PageRight.started += instance.OnPageRight;
            @PageRight.performed += instance.OnPageRight;
            @PageRight.canceled += instance.OnPageRight;
            @Accept.started += instance.OnAccept;
            @Accept.performed += instance.OnAccept;
            @Accept.canceled += instance.OnAccept;
            @Cancel.started += instance.OnCancel;
            @Cancel.performed += instance.OnCancel;
            @Cancel.canceled += instance.OnCancel;
            @Level1.started += instance.OnLevel1;
            @Level1.performed += instance.OnLevel1;
            @Level1.canceled += instance.OnLevel1;
            @Level2.started += instance.OnLevel2;
            @Level2.performed += instance.OnLevel2;
            @Level2.canceled += instance.OnLevel2;
            @Level3.started += instance.OnLevel3;
            @Level3.performed += instance.OnLevel3;
            @Level3.canceled += instance.OnLevel3;
        }

        private void UnregisterCallbacks(IGeneralActions instance)
        {
            @Submit.started -= instance.OnSubmit;
            @Submit.performed -= instance.OnSubmit;
            @Submit.canceled -= instance.OnSubmit;
            @Navigation.started -= instance.OnNavigation;
            @Navigation.performed -= instance.OnNavigation;
            @Navigation.canceled -= instance.OnNavigation;
            @PageLeft.started -= instance.OnPageLeft;
            @PageLeft.performed -= instance.OnPageLeft;
            @PageLeft.canceled -= instance.OnPageLeft;
            @PageRight.started -= instance.OnPageRight;
            @PageRight.performed -= instance.OnPageRight;
            @PageRight.canceled -= instance.OnPageRight;
            @Accept.started -= instance.OnAccept;
            @Accept.performed -= instance.OnAccept;
            @Accept.canceled -= instance.OnAccept;
            @Cancel.started -= instance.OnCancel;
            @Cancel.performed -= instance.OnCancel;
            @Cancel.canceled -= instance.OnCancel;
            @Level1.started -= instance.OnLevel1;
            @Level1.performed -= instance.OnLevel1;
            @Level1.canceled -= instance.OnLevel1;
            @Level2.started -= instance.OnLevel2;
            @Level2.performed -= instance.OnLevel2;
            @Level2.canceled -= instance.OnLevel2;
            @Level3.started -= instance.OnLevel3;
            @Level3.performed -= instance.OnLevel3;
            @Level3.canceled -= instance.OnLevel3;
        }

        public void RemoveCallbacks(IGeneralActions instance)
        {
            if (m_Wrapper.m_GeneralActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGeneralActions instance)
        {
            foreach (var item in m_Wrapper.m_GeneralActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GeneralActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GeneralActions @General => new GeneralActions(this);
    private int m_KeyboardSchemeIndex = -1;
    public InputControlScheme KeyboardScheme
    {
        get
        {
            if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
            return asset.controlSchemes[m_KeyboardSchemeIndex];
        }
    }
    private int m_GamepadSchemeIndex = -1;
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    public interface IRumbleActions
    {
        void OnRumbleAction(InputAction.CallbackContext context);
    }
    public interface IButtonsActions
    {
        void OnAccelerate(InputAction.CallbackContext context);
        void OnBrake(InputAction.CallbackContext context);
        void OnLBumper(InputAction.CallbackContext context);
        void OnRBumper(InputAction.CallbackContext context);
        void OnLDrift(InputAction.CallbackContext context);
        void OnRDrift(InputAction.CallbackContext context);
        void OnItem(InputAction.CallbackContext context);
        void OnEditVehicle(InputAction.CallbackContext context);
        void OnLeaderboard(InputAction.CallbackContext context);
        void OnSetLang(InputAction.CallbackContext context);
        void OnHonk(InputAction.CallbackContext context);
        void OnStartGame(InputAction.CallbackContext context);
    }
    public interface IGeneralActions
    {
        void OnSubmit(InputAction.CallbackContext context);
        void OnNavigation(InputAction.CallbackContext context);
        void OnPageLeft(InputAction.CallbackContext context);
        void OnPageRight(InputAction.CallbackContext context);
        void OnAccept(InputAction.CallbackContext context);
        void OnCancel(InputAction.CallbackContext context);
        void OnLevel1(InputAction.CallbackContext context);
        void OnLevel2(InputAction.CallbackContext context);
        void OnLevel3(InputAction.CallbackContext context);
    }
}
